<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0105EN-SkillsNetwork/labs/Module2/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


# My Jupyter Notebook on IBM Watson Studio


**Brian Ingram**  
Data Scientist

*I am interested in Data Science because I have the skills and insight to extract the mystery in large sets of data and to use that mystery to develop story lines that have the potential to change the world for the better.* 

### My code below is a brief introduction into linear algebra.  We will reproduce a matrix and find the transpose of the matrix and it's multiplicative inverse using the numpy package in Python. Linear algebra is very relevant in Data Science because linear algebra serves as the basis for concepts like Principal Component Analysis (PCA) and application of Artificial Neural Networks to Computer Vision problems.

In [5]:
import numpy as np
A = np.matrix('2 4 7; 8 15 36')
print("Matrix is :\n", A)
#Transpose of matrix
print("The transpose of matrix A is :\n", A.getT())
#Multiplicative inverse
print("Multiplicative inverse of matrix A is :\n", A.getI())

Matrix is :
 [[ 2  4  7]
 [ 8 15 36]]
The transpose of matrix A is :
 [[ 2  8]
 [ 4 15]
 [ 7 36]]
Multiplicative inverse of matrix A is :
 [[ 0.30656934 -0.05839416]
 [ 0.79730488 -0.1555306 ]
 [-0.40033689  0.10555867]]


You can learn more about these concepts <a href="https://www.katjaas.nl/transpose/transpose.html">here</a>.

There is a famous quote by Kaplansky on linear algebra:

>We [he and Halmos] share a philosophy about linear algebra: we think basis-free, we write basis-free, but when the chips are down we close the office door and compute with matrices like fury. (Paul Halmos: Celebrating 50 Years of Mathematics.)